### ISSUE TITLE
ModuleNotFoundError: No module named model_speech

### ISSUE THREAD

**Issue by lxxiv** [jhuang448/E2E-LyricsAlignment-Implementation#1]
Hello,

I've been trying this repo tonight and I can't get past an issue after running the python test.py --data_dir command 

It shows "from model_speech import train_audio_transforms" 
ModuleNotFound: no module named "model_speech"
(Screenshot attached below)
<img width="680" alt="Screen Shot 2021-04-05 at 10 32 23 PM" src="https://user-images.githubusercontent.com/60582320/113625054-b1dcda80-9660-11eb-8cf3-ea06af7516ac.png">

Any idea how to solve this? I tried looking online for a module I need to install but nothing pops up with that name.

Would appreciate any help.

**Comment by jhuang448** [comment]
This line is not used. Simply removing it should solve the problem.
